t:
    print("ERROR....")

finally: 
    conn.close()